// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn8k-4pjoOxN-ktcDfb14NdaqhVmRWQIY',
    appId: '1:69330544530:web:cdae8524201cfcf553c34b',
    messagingSenderId: '69330544530',
    projectId: 'smart-queue-polinema',
    authDomain: 'smart-queue-polinema.firebaseapp.com',
    databaseURL: 'https://smart-queue-polinema-default-rtdb.firebaseio.com',
    storageBucket: 'smart-queue-polinema.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXKLSqCVjbtjT2EFFS-LWS1LCAko0BOcg',
    appId: '1:69330544530:android:4af257e89f5e27f953c34b',
    messagingSenderId: '69330544530',
    projectId: 'smart-queue-polinema',
    databaseURL: 'https://smart-queue-polinema-default-rtdb.firebaseio.com',
    storageBucket: 'smart-queue-polinema.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCA9KVWO7Y2G8aJhoF2KuiE6VU08SxZDA',
    appId: '1:69330544530:ios:b26d5ed1611eb82453c34b',
    messagingSenderId: '69330544530',
    projectId: 'smart-queue-polinema',
    databaseURL: 'https://smart-queue-polinema-default-rtdb.firebaseio.com',
    storageBucket: 'smart-queue-polinema.firebasestorage.app',
    iosBundleId: 'com.example.smartQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCA9KVWO7Y2G8aJhoF2KuiE6VU08SxZDA',
    appId: '1:69330544530:ios:b26d5ed1611eb82453c34b',
    messagingSenderId: '69330544530',
    projectId: 'smart-queue-polinema',
    databaseURL: 'https://smart-queue-polinema-default-rtdb.firebaseio.com',
    storageBucket: 'smart-queue-polinema.firebasestorage.app',
    iosBundleId: 'com.example.smartQueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn8k-4pjoOxN-ktcDfb14NdaqhVmRWQIY',
    appId: '1:69330544530:web:e1b255b5d2589fc153c34b',
    messagingSenderId: '69330544530',
    projectId: 'smart-queue-polinema',
    authDomain: 'smart-queue-polinema.firebaseapp.com',
    databaseURL: 'https://smart-queue-polinema-default-rtdb.firebaseio.com',
    storageBucket: 'smart-queue-polinema.firebasestorage.app',
  );

}